"""empty message

Revision ID: 7e9f79fafda9
Revises: f4d86800463d
Create Date: 2024-09-27 22:41:30.157876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9f79fafda9'
down_revision = 'f4d86800463d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
