"""Modify create_date field

Revision ID: cb593de36ac4
Revises: 439d0fb6406b
Create Date: 2024-09-22 22:23:53.582481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb593de36ac4'
down_revision = '439d0fb6406b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
